### ISSUE TITLE
Catalina install issue

### ISSUE THREAD

**Issue by labrat789** [arb-project/homebrew-arb#5] opened 2020-10-26 12:20 UTC
Hi, I seem to be having an issue installing on Catalina (10.15.7). It seems to be having an issue compiling GDE?

jones@213-31-ultuna ~ %         brew install arb-project/arb/arb
==> Installing arb from arb-project/arb
==> Downloading http://download.arb-home.de/special/manual-builds/2020_03_03/arb-r18342-source.tgz
Already downloaded: /Users/jones/Library/Caches/Homebrew/downloads/0edd4c7052b50c1ba2914cfb3de27ae7a5b0dca6fc17b8bb5128382a99bf0215--arb-r18342-source.tgz
==> Patching
==> make rebuild ARB_64=1 OPENGL=0 MACH=DARWIN DARWIN=1 LINUX=0 DEBIAN=0 REDHAT=0 DEBUG=0
Last 15 lines from /Users/jones/Library/Logs/Homebrew/arb/01.make:

Done.
 /usr/local/opt/coreutils/bin/gmkdir -p '/private/tmp/arb-20201026-27914-1ah2edj/arbsrc_18342/bin'
  /usr/local/opt/coreutils/bin/ginstall -c phyml '/private/tmp/arb-20201026-27914-1ah2edj/arbsrc_18342/bin/./phyml_20130708'
make[9]: Nothing to be done for `install-data-am'.
make[9]: Nothing to be done for `install-exec-am'.
make[9]: Nothing to be done for `install-data-am'.
rm -f phyml.stamp
test -f /private/tmp/arb-20201026-27914-1ah2edj/arbsrc_18342/bin/phyml_20130708 || /Library/Developer/CommandLineTools/usr/bin/make retry
[15:38.N] ------------------------------------------------ Make PHYML20130708 [done]
make[4]: *** [GDE.a] Error 2
make[3]: *** [GDE/GDE.dummy] Error 1
make[2]: *** [arb] Error 2
make[1]: *** [all] Error 2
make: *** [rebuild] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/arb-project/homebrew-arb/issues

Any feedback would be much appreciated, and let me know if you need more info.

thanks,
Chris

**Comment by jgerken** [comment] 2020-10-26 22:26
I just ran an automatic test in a GitHub virtual machine with macOS 10.15.7. This test was successful and did not reproduce your problem. Therefore, I think it is an incompatibility issue caused by something else installed on your system. Could you attach all log files from the directory ˋ/Users/jones/Library/Logs/Homebrew/arb/ˋ to the ticket, please. The summary given by brew on the command line does not contain the important what exactly failed, unfortunately.

**Comment by labrat789** [comment] 2020-10-27 08:55
Hi, thanks for the fast response. 

Here are the files - FYI, I have been able to get a macports install to work, but I tried the homebrew install _before_ switching to macports and still got this error. Naturally I'd rather stick to homebrew's more updated ARB install.

Thanks again for the help, hopefully it's not something stupid that I've done (entirely plausible).

Chris

[Archive.zip](https://github.com/arb-project/homebrew-arb/files/5444031/Archive.zip)

**Comment by jgerken** [comment] 2020-10-27 13:22
After upgrading to macOS Catalina, too. I can now reproduce the issue locally. Not sure why it does not happen in the GitHub VM. Need to debug that.

The same problem has occurred for MacPorts builds, too. Therefore, a fix was added to ARB. The fix is included in the HEAD version of ARB only. Please run

```
brew install --HEAD arb-project/arb/arb
```

The installation may fail initially, at least it did for me, and ask you to run `brew install svn`. But after that it works.

Sorry for the inconvenience!

**Comment by labrat789** [comment] 2020-10-27 14:27
Sweet! works like a charm. Thanks again for the rapid response.

**Comment by jgerken** [comment] 2020-11-10 20:04
The problem is now fixed in the production version, too. If you want to switch back to the production version run

```
brew unlink arb-project/arb/arb
brew install arb-project/arb/arb
```

**Closed as completed by jgerken** 2020-11-10 20:04 UTC
