### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by heisersa** [arb-project/homebrew-arb#22] opened 2023-05-22 21:59 UTC
Dear all,
I am quite new to using command line in terminal, so I apologize if this is (likely) user error, but I am not getting anywhere further with google ...
I have been trying to install ARB with the following line, but it comes up with an error message: brew install arb-project/arb/arb@7
(I did also install xquartz first)

I have a MacBook Pro (2017) and run Ventura 13.3.1 (a) - I was wondering whether that may be the issue?

I have attached the logs from when I tried to install arb (as text files below, after I copied the output in the terminal - I am assuming it is mostly the same, but just in case it is not, I did both).
Please let me know if you need to know anything else. I appreciate the help.
Best wishes,
Sabrina

==> Downloading http://download.arb-home.de/build/arb-7.0.1/arb-7.0.1-source.tgz
Already downloaded: /Users/sabrina.heiser/Library/Caches/Homebrew/downloads/5e6bd4bb3c5466aec02dd082ffd4025ee71f80829887735e0ee071d89ee0ea3f--arb-7.0.1-source.tgz
==> Installing arb@7 from arb-project/arb
==> Patching
==> make all ARB_64=1 OPENGL=1 MACH=DARWIN DARWIN=1 LINUX=0 DEBIAN=0 REDHAT=0 DEBUG=0 TRACESYM=1
Last 15 lines from /Users/sabrina.heiser/Library/Logs/Homebrew/arb@7/01.make:
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_root.o ED4_root.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_root.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_search.o ED4_search.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_search.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_seq_colors.o ED4_seq_colors.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_seq_colors.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_terminal.o ED4_terminal.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_terminal.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_text_terminals.o ED4_text_terminals.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_text_terminals.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_tools.o ED4_tools.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_tools.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_visualizeSAI.o ED4_visualizeSAI.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_visualizeSAI.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o ED4_window.o ED4_window.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 ED4_window.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o EDB_root_bact.o EDB_root_bact.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 EDB_root_bact.cxx
clang++ -O3  -arch x86_64  -pipe -fmessage-length=0 -fshow-column -funit-at-a-time -fPIC -fno-common -fstrict-aliasing -DARB_OPENGL  -W -Wall -DNDEBUG -DARB_64 -DDARWIN   -Wwrite-strings -Wunused -Wno-aggregate-return -DIN_ARB_EDIT4  -Wnon-virtual-dtor -Wreorder -Wpointer-arith -Wdisabled-optimization -Wmissing-format-attribute -Wctor-dtor-privacy -Wmissing-noreturn -Winit-self -Wstrict-aliasing -Wextra -Weffc++ -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init -c -o graph_aligner_gui.o graph_aligner_gui.cxx  -I. -I/private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/INCLUDE -I/include -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/System/Library/Frameworks/GLUT.framework/Headers -I/System/Library/Frameworks/OpenGL.framework/Headers -I/usr/include/krb5 -I/usr/local/Cellar/pcre2/10.42/include -I/usr/local/Cellar/glib/2.76.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.76.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include 2>&1 | /private/tmp/arbA7-20230522-10633-1dgowkl/arbsrc_18910/SOURCE_TOOLS/postcompile.pl --compiler=14.0.3 graph_aligner_gui.cxx
ar -csq EDIT4.a ED4_ProteinViewer.o ED4_base.o ED4_block.o ED4_colStat.o ED4_consensus.o ED4_container.o ED4_cursor.o ED4_dots.o ED4_dump.o ED4_edit_string.o ED4_flags.o ED4_main.o ED4_manager.o ED4_naligner.o ED4_nds.o ED4_no_class.o ED4_objspec.o ED4_plugins.o ED4_protein_2nd_structure.o ED4_root.o ED4_search.o ED4_seq_colors.o ED4_terminal.o ED4_text_terminals.o ED4_tools.o ED4_visualizeSAI.o ED4_window.o EDB_root_bact.o graph_aligner_gui.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: EDIT4.a(ED4_dump.o) has no symbols
[41:58.N] ------------------------------------------------ Make EDIT4 [done]
make[1]: *** [arb] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/arb-project/homebrew-arb/issues

[01.make.cc.txt](https://github.com/arb-project/homebrew-arb/files/11537363/01.make.cc.txt)
[01.make.txt](https://github.com/arb-project/homebrew-arb/files/11537364/01.make.txt)

**Comment by jgerken** [comment] 2023-05-23 17:05
The build script for ARB 7 is not compatible with macOS Ventura. It is fixed in the beta version of ARB 7.1, which can be installed via

```
brew install arb-project/arb/arb
```

However, this did not work on my Mac when I tried a minute ago but still worked in March. I am not sure if I made changes to my system which prevents building ARB or if it due to updates from Apple. Can you please try if the above-mentioned install command works for you?

**Comment by heisersa** [comment] 2023-05-23 17:14
Thank you for responding so quickly.
It comes up with an error as well (I failed to mention that I had tried the different versions listed on github).

Let me know if the logs help and I can send them.
I can also see whether we have a computer with an older macO version that I can use to solve the issue for myself temporarily - if it wasn't something I did wrong on my side for now.

**Comment by NF-H** [comment] 2023-07-11 08:04
My colleague and I also have the same issue.

I have a M2 mac mini (Ventura 13.4.1). My colleague has a M2 macbook air (Ventura 13.4.1).

**Comment by jgerken** [comment] 2023-07-16 00:11
I finally was able to figure the root cause of the issue. Apple added `-Werror=implicit-function-declaration` to the default `clang` options - probably with Xcode 14. This change is not compatible with the partially decades old source code of ARB. Locally I was able to revert Apple's change by setting `-Wno-error=implicit-function-declaration`. I have contacted the ARB maintainer how to proceed best on this issue. Thus, I have not released a new version of the formula.

If you need to install ARB before I release a new version of the formula, you can apply the workaround I used by executing the following command:

```
brew edit arb-project/arb/arb
```

and adding the following lines at the end of the file that opens:

```
diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -700,6 +700,7 @@ dflags += -D$(MACH) # define machine

 ifeq ($(DARWIN),1)
  shared_cflags += -fno-common
+ cflags +=  -Wno-error=implicit-function-declaration
 else
  dflags +=  $(shell getconf LFS_CFLAGS)
 endif
diff --git a/GDE/SATIVA/Makefile b/GDE/SATIVA/Makefile
--- a/GDE/SATIVA/Makefile
+++ b/GDE/SATIVA/Makefile
@@ -58,7 +58,7 @@ build:  $(VERSIONS:%=$(RAXML_BIN)%)
 #  which are needed by RAxML)

 $(RAXML_BIN)%: unpack.%.stamp Makefile
-	( MAKEFLAGS= $(MAKE) -C $(<:unpack.%.stamp=builddir.%) -f Makefile.$(@:$(RAXML_BIN)%=%).$(MAKE_SUFFIX) ) 2>&1 | grep -vi ' warning: '
+	( MAKEFLAGS= $(MAKE) -C $(<:unpack.%.stamp=builddir.%) -f Makefile.$(@:$(RAXML_BIN)%=%).$(MAKE_SUFFIX) CFLAGS="-Wno-error=implicit-function-declaration" ) 2>&1 | grep -vi ' warning: '
 	cp $(<:unpack.%.stamp=builddir.%)/raxmlHPC-* $@

 unpack.%.stamp: $(TARFILE)

```

**Comment by jgerken** [comment] 2023-07-16 18:44
I have released a new version of the formula which fixes the problem. The ARB sources will be updated at a later point in time.

**Closed as completed by jgerken** 2023-07-16 18:44 UTC
